name: Build
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - "*.md"
      - "*.yaml"
      - .editorconfig
      - ".forgejo/**"
      - .gitignore
  pull_request:
    branches:
      - main
    paths-ignore:
      - "*.md"
      - "*.yaml"
      - .editorconfig
      - ".forgejo/**"
      - .gitignore
jobs:
  build:
    name: cargo build
    runs-on: codeberg-small
    steps:
      - uses: actions/checkout@v4
      - name: Prepare Rust toolchain
        uses: https://codeberg.org/wackbyte/rust-toolchain@trunk
        with:
          toolchain: nightly
          components: clippy
      - name: cargo build
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: cargo test
        run: cargo test --all-features
