name: Build
on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - "[0-9]+.[0-9]+.[0-9]+*"
    paths-ignore:
      - "*.md"
      - "*.yaml"
      - .editorconfig
      - ".forgejo/**"
      - .gitignore
  pull_request:
    branches:
      - main
    paths-ignore:
      - "*.md"
      - "*.yaml"
      - .editorconfig
      - ".forgejo/**"
      - .gitignore
jobs:
  build:
    name: cargo build
    runs-on: docker
    container:
      image: ghcr.io/catthehacker/ubuntu:custom-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: https://github.com/DeterminateSystems/nix-installer-action.git@main
      - name: Set user for Cachix
        run: echo "USER=root" >> $GITHUB_ENV
      - name: Set up cache
        uses: https://github.com/cachix/cachix-action.git@v15
        with:
          name: cmha
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Build and test x86_64
        run: make target/tmp/cmha_x86_64
      - name: Build and test aarch64
        run: make target/tmp/cmha_aarch64
      - name: Upload binaries
        if: success() && forgejo.event_name != 'pull_request' && startsWith(forgejo.ref, 'refs/tags/')
        uses: https://code.forgejo.org/forgejo/upload-artifact@v5
        with:
          name: binaries
          path: target/tmp/
  deploy:
    name: deploy
    needs: [build]
    if: success() && forgejo.event_name != 'pull_request' && startsWith(forgejo.ref, 'refs/tags/')
    runs-on: codeberg-small
    container:
      image: debian:trixie
      env:
        BUILDAH_ISOLATION: chroot
    steps:
      - name: Install tools
        run: |
          apt-get update
          apt-get install buildah git nodejs docker-cli make wget -y
          wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -qO /usr/local/bin/yq && chmod +x /usr/local/bin/yq
      - uses: actions/checkout@v4
      - name: Download binaries
        uses: https://code.forgejo.org/forgejo/download-artifact@v7
        with:
          name: binaries
          path: target/tmp/
      - name: Setup buildah
        uses: https://codeberg.org/qikp/setup-buildah@main
      - name: Login to Docker Hub
        uses: https://github.com/docker/login-action.git@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        run: make
