name: Build
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - "*.md"
      - "*.yaml"
      - .editorconfig
      - ".forgejo/**"
      - .gitignore
  pull_request:
    branches:
      - main
    paths-ignore:
      - "*.md"
      - "*.yaml"
      - .editorconfig
      - ".forgejo/**"
      - .gitignore
jobs:
  build:
    name: cargo build
    runs-on: docker
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: https://github.com/DeterminateSystems/nix-installer-action.git@main
      - name: Set USER for Cachix
        run: echo "USER=root" >> $GITHUB_ENV
      - name: Set up cache
        uses: https://github.com/cachix/cachix-action.git@v15
        with:
          name: cmha
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Build and test
        run: nix build --print-build-logs
